---
title: "MC-Proj1"
author: "Alicja Wiączkowska"
date: "2024-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = T)
```


## LCG

*tekst*
```{r LCG}
LCG<-function(n, M,a,c, x){
  # n - liczba generowanych liczb
  randoms<-numeric(n)
  for(i in 1:n){
    x = (a*x+c) %% M
    randoms[i]<-x
  }
  return(randoms)
}
```


```{r LCG2}
LCG(20, 13,1,5, 0)
LCG(10, 2^10,3,7, 0)
```


## GLCG

```{r GLCG}
library(data.table)
GLCG<-function(n, M,a_wek, x_wek){
  # n - liczba generowanych liczb
  randoms<-numeric(n)
  x <- rev(x_wek) # uporządkowujemy indeksy malejąco
  L<- length(x)
  for(i in 1:n){
    xi = sum(a_wek*x) %% M
    randoms[i]<-xi
    x<-shift(x, n=1, fill=xi, type="lag")
  }
  return(randoms)
}
```

```{r}
a=c(3,7,68)
M=2**10
n=5
x_wek=1:3
GLCG(20,2**10, c(3,7,68), 1:3)
```

## RC4(m)

*tekst*
```{r KSA}
m=32
#Key Schelduling Alghoritm
KSA <-function(Key){
  # przyjmuje klucz sortowania, zwraca permutację
  L=length(Key)
  S=c( 0 : (m-1)) # {0,1,..,m-1}
  j = 0
  for( i in 1:m){
       j = (j + S[i+1] + Key[i %% L]) %% m
       
        # swap ( S[j+1], S[i+1] )
        temp=S[j+1]
        S[j+1]<-S[i+1]
        S[i+1]<-temp
  }
   return(S)  
}

```

```{r RC4}
m = 32

RK4<-function(n, seed=c(0,0), S=c( 0 : (m-1)) ){
  # liczba generowanych liczb losowych
  randoms = numeric(n)
  i=seed[1]; j=seed[2]
  for( iter in 1:n){
    
    i = (i+1) %%m
    j = ( j+S[i+1] ) %%m  # indeksy są liczone od 1 w R 
  
    # swap ( S[j+1], S[i+1] )
    temp=S[j+1]
    S[j+1]<-S[i+1]
    S[i+1]<-temp
    
    t <- (S[i+1]+S[j+1]) %%m
    randoms[iter] <- S[t+1]
  }
  return(randoms)
}
```

```{r}
RK4(5); RK4(15); RK4(45)

par(mfrow=c(1,2))
hist(RK4(100)/32)
hist(runif(100))

par(mfrow=c(1,2))
hist(RK4(1000)/32)
hist(runif(1000))
```


## Testy

```{r}
library(randtoolbox)
# test kolizji
?coll.test.sparse
?coll.test


?ks.test


```



## Źródła
https://ipsec.pl/files/ipsec/ving-krypto.pdf   str 7

"Theory and Practice of Monte Carlo Methods" 
Paweł Lorek Tomasz Rolski

